sequenceDiagram
    User->>QuantusSoftware: Get the Auto-Zero settings
    QuantusSoftware->>User: Return the Auto-Zero settings
    User->>QuantusSoftware: Change and Update the Auto-Zero settings
    User->>QuantusSoftware: Apply the Auto-Zero settings
    Note over User,QuantusSoftware: Repeat above sequence for channels requiring Auto-Zero changes
            